version: "3"

services:
  postgres:
    image: "postgres:14-alpine"
    container_name: postgres-14
    environment:
      POSTGRES_USER: padmin
      POSTGRES_PASSWORD: padmin
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadm4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    name: postgres-network
    driver: bridge

volumes:
  postgres:
    name: p14-data
  pgadmin:
    name: pgadm-data
